spring:
  application:
    name: "api"
  datasource:
    url: jdbc:mariadb://localhost:3306/digitalisation
    username: hackaton
    password: hackaton
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: maria
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB